###########
# Modules #
###########

# The reserch nature of this project dictates the modular approach to
# configure simulations with everything they need and no more than that.
# The layout of each module is what ns3 suggests:
# - tests/ with local module-related tests
# - model/ with actual code
# - helpers/ with helpers to setup models
# - docs/ with docs if dev was not too lazy to write it

# Core is common code for extension modules and simulator in general.
subdir('core')

# Here all extension modules go.
subdir('extensions/radio')
subdir('extensions/its-g5')
